### ISSUE TITLE
error while zoomed out

### ISSUE THREAD

**Issue by qlesz** [mikepauer/Carbonite.Notes#3]
I was zooming out to see if new maps has been added and get this error:

Date: 2018-07-28 19:39:39
ID: 35
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite.Notes\NxFav.lua line 1456:
   attempt to call global 'GetCurrentMapDungeonLevel' (a nil value)
Debug:
   Carbonite.Notes\NxFav.lua:1456: UpdateIcons()
   Carbonite\NxMap.lua:4874: Update()
   Carbonite\NxMap.lua:3848:
      Carbonite\NxMap.lua:3732
Locals:
self = <table> {
 RecordAnimTimer = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:346
 OnButToggleFav = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1576
 IMenu_OnRename = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:544
 HandyNotes = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1509
 FindFav = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:987
 ToggleShow = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:646
 GetParent = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:943
 Create = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:235
 Menu_OnPaste = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:505
 SetRecord = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:324
 ParseItemNote = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1132
 GetIconFile = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:215
 OnChat_msg_addon = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:152
 Update = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:768
 GetIconInline = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:210
 Menu_OnAddFavorite = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:453
 But_OnItemDel = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:393
 GetNoteFav = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1253
 But_OnRecord = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:320
 But_OnDown = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:359
 Menu_OnRename = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:463
 MakeXY = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1121
 AddFavorite = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1076
 Record = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1211
 But_OnUp = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:355
 MoveCur = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:363
 OpenFoldersToFav = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1006
 IMenu_OnCopy = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:570
 IMenu_OnCut = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:557
 OnItemListEvent = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:732
 AddNote = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1597
 SetNoteAtStr = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1274
 IMenu_OnAddComment = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:534
 Draw = false
 SetItemFlags = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1157
 OnEditBox = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:663
 UpdateIcons = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1411
 UpdateItems = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:858
 AddonNote = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1601
 UpdateFolder = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:818
 ParseItem = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1126
 NoteIcons = <table> {
 }
 Menu_OnAddNote = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1588
 Folders = <table> {
 }
 Menu_OnCopy = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:497
 CreateItem = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1104
 IMenu_OnPaste = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:577
 Menu_OnCut = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:478
 DrawMapId = 84
 UpdateTargets = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1361
 ShowIconNote = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1336
 AddFolder = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1060
 SelectCur = <function> defined @Int
AddOns:
  Swatter, v7.7.6000 (SwimmingSeadragon)
  AtlasLoot, vv8.07.13
  AtlasLootCataclysm, vv8.07.13
  AtlasLootClassic, vv8.07.13
  AtlasLootLegion, vv8.07.13
  AtlasLootMistsofPandaria, vv8.07.13
  AtlasLootWarlordsofDraenor, vv8.07.13
  AtlasLootWrathoftheLichKing, vv8.07.13
  AucAdvanced, v7.7.6000 (SwimmingSeadragon)
  AucFilterBasic, v7.7.6000 (SwimmingSeadragon)
  AucScanData, v7.7.6000 (SwimmingSeadragon)
  AucStatHistogram, v7.7.6000 (SwimmingSeadragon)
  AucStatiLevel, v7.7.6000 (SwimmingSeadragon)
  AucStatPurchased, v7.7.6000 (SwimmingSeadragon)
  AucStatSimple, v7.7.6000 (SwimmingSeadragon)
  AucStatStdDev, v7.7.6000 (SwimmingSeadragon)
  AucUtilFixAH, v7.7.6000 (SwimmingSeadragon)
  BadBoy, vv8.0.7
  BadBoyCCleaner, vv8.0.0
  Bartender4, v4.8.1
  BeanCounter, v7.7.6000 (SwimmingSeadragon)
  BuyEmAll, v3.5.0
  Carbonite, v8.0.0
  CarboniteInfo, v7.3.0
  CarboniteNotes, v7.3.0
  CarboniteQuests, v8.0.0
  CarboniteSocial, v7.3.0
  CarboniteWarehouse, v7.3.0
  CarboniteWeekly, v7.3.0
  CTATracker, v
  DBMCore, v8.0.1
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsRaidInfoEmeraldNightmare, v
  DetailsRaidInfoNighthold, v
  DetailsRaidInfoTombOfSargeras, v
  DetailsRaidInfoTrialOfValor, v
  DetailsStreamer, v
  DetailsTargetCaller, v
  DetailsTimeAttack, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Enchantrix, v7.7.6000 (SwimmingSeadragon)
  EnchantrixBarker, v7.7.6000 (SwimmingSeadragon)
  epgp, vv5.12.17
  epgplootmaster, v6.71
  epgplootmasterml, v6.71
  GearCheck, vv4.4
  GottaGoFast, v30000
  GottaGoFastHistory, v30000
  HandyNotes, vv1.5.2
  HandyNotesArgus, v0.20.0
  HandyNotesBrokenShore, vv1.27
  HandyNotesDraenorTreasures, v1.21
  HandyNotesLegionTreasures, v1
  MoveAnything, v17.0.0
  OmniCC, v8.0.1
  Overachiever, v1.0.0
  OverachieverTabs, v1.0.0
  Pawn, v2.2.22
  PersonalLootHelper, v2.08
  Postal, vv3.6.0
  Prat30, vr1161      
  Prat30Libraries, v
  RaiderIO, v8.0.1 (v201807280600)
  RaiderIODBEUA, v
  RaiderIODBEUH, v
  SavedInstances, v8.0.3
  SimpleTauntAnnounce, v1.0.38
  Skillet, v4.02
  SlideBar, v7.7.6000 (SwimmingSeadragon)
  Stubby, v7.7.6000 (SwimmingSeadragon)
  TellMeWhen, v8.5.1
  TellMeWhenOptions, v
  TidyPlates, v6.18.11
  TidyPlatesGraphite, v
  TidyPlatesGrey, v
  TidyPlatesNeon, v
  TidyPlatesQuatre, v
  TidyPlatesHub, v
  TidyPlatesWidgets, v
  WeakAuras, v2.6.4
  WorldQuestTracker, v
  WoWProgressLink, v1.26
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=9f3)

Also after error i could not zoom in close enough to see area maps (only world maps were visible)

**Comment by IrcDirk** [comment]
Notes are not updated to 8.x yet.
