### ISSUE TITLE
error when trying to modify note

### ISSUE THREAD

**Issue by qlesz** [mikepauer/Carbonite.Notes#4]
as in title i'm getting this error when trying to modify any note or list all existing notes. `GetMapNameByID` has been replaced a while ago with `C_Map.GetMapInfo(uiMapID)` but unfortunatelly im not familiar with LUA.

Date: 2020-10-25 11:07:41
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite.Notes\NxFav.lua line 918:
   attempt to call global 'GetMapNameByID' (a nil value)
Debug:
   [string "@Carbonite.Notes\NxFav.lua"]:918: UpdateItems()
   [string "@Carbonite.Notes\NxFav.lua"]:1218: SelectItems()
   [string "@Carbonite.Notes\NxFav.lua"]:705: UserFunc()
   [string "@Carbonite\NxUI.lua"]:6502:
      Carbonite\NxUI.lua:6481
Locals:
self = <table> {
 RecordAnimTimer = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:361
 OnButToggleFav = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1598
 IMenu_OnRename = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:559
 HandyNotes = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1524
 FindFav = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1002
 ToggleShow = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:661
 GetParent = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:958
 Create = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:250
 Menu_OnPaste = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:520
 Menu = <table> {
 }
 SetRecord = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:339
 ParseItemNote = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1147
 GetIconFile = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:214
 OnChat_msg_addon = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:152
 Update = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:783
 GetIconInline = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:209
 Menu_OnAddFavorite = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:468
 But_OnItemDel = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:408
 GetNoteFav = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1268
 But_OnRecord = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:335
 But_OnDown = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:374
 Menu_OnRename = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:478
 MakeXY = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1136
 AddFavorite = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1091
 ItemMenu = <table> {
 }
 Record = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1226
 But_OnUp = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:370
 MoveCur = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:378
 OpenFoldersToFav = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1021
 IMenu_OnCopy = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:585
 IMenu_OnCut = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:572
 FavCnt = 5
 OnItemListEvent = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:747
 AddNote = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1619
 SetNoteAtStr = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1289
 IMenu_OnAddComment = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:549
 Draw = true
 SetItemFlags = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1172
 OnEditBox = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:678
 UpdateIcons = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1426
 CurItemI = 1
 UpdateItems = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:873
 CurFav = <table> {
 }
 CurFolder = <table> {
 }
 AddonNote = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1623
 ItemList = <table> {
 }
 IMenu_OnPaste = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:592
 UpdateFolder = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:833
 ParseItem = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1141
 RecBut = <table> {
 }
 Win = <table> {
 }
 Side = 1
 InstLevelSet = 0
 NoteIcons = <table> {
 }
 Menu_OnAddNote = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1610
 Folders = <table> {
 }
 Menu_OnCopy = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:512
 CreateItem = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:1119
 List = <table> {
 }
 Menu_OnCut = <function> defined @Interface\AddOns\Carbonite.Notes\NxFav.lua:493
 DrawMapId = 864
 UpdateTargets = <function> defined @Interface\

**Comment by IrcDirk** [comment]
Try now ;)

**Comment by qlesz** [comment]
fixed. closing.
